### ISSUE TITLE
align image

### ISSUE THREAD

**Issue by thuc201995** [jpuri/react-draft-wysiwyg#520]
can you make alignment image like this [https://support.strikingly.com/hc/user_images/LParp6lfPpiAb_XNy_dMBA.jpeg](url)

**Comment by jpuri** [comment]
That looks hard with draftjs :( but I will check.

**Comment by thuc201995** [comment]
I think you can try make a new button and add class to image with css like
float :left -.-

**Comment by gregBerthelot** [comment]
Seems to be related to https://github.com/jpuri/react-draft-wysiwyg/issues/227 which is pending since 9 months now.

**Comment by jsiebern** [comment]
It seems you can accomplish this rather easy with some CSS (mostly behaves like `draftToHtml` with this):

```css
.editor-class figure {
    margin: 0;
}
.editor-class .rdw-image-left {
    display: unset;
    float: left;
}
.editor-class .rdw-image-right {
    display: unset;
    justify-content: unset;
    float: right;
}
```
