### ISSUE TITLE
UX bug in example

### ISSUE THREAD

**Issue by thehappycoder** [jpuri/react-draft-wysiwyg#724]
When you open https://jpuri.github.io/react-draft-wysiwyg/#/ in Mobile Safari and tap "Start typing", the editor gets focused. However, if you tap somewhere below the first invisible row, you can't focus it to start typing. It's fine in Android Chrome.

The workaround is to set minimum height to a `.public-DraftEditor-content` instead.

**Comment by alfaslash** [comment]
> When you open https://jpuri.github.io/react-draft-wysiwyg/#/ in Mobile Safari and tap "Start typing", the editor gets focused. However, if you tap somewhere below the first invisible row, you can't focus it to start typing. It's fine in Android Chrome.

I have the same problem.

**Comment by peresleguine** [comment]
One way to fix this is to set fixed height on `editorClassName`:
```css
.home-editor {
  height: 200px;
}
```

I also came up with the min-height/max-height solution which I like better:
```css
.home-editor {
  height: auto;
  min-height: 200px;
  max-height: 400px;
}

.DraftEditor-editorContainer,
.DraftEditor-root,
.public-DraftEditor-content {
  min-height: inherit;
}
```
