### ISSUE TITLE
Possibility to remove highlight from colorpicker

### ISSUE THREAD

**Issue by FaresAbu-Khiarah** [jpuri/react-draft-wysiwyg#728]
Hi,

first of all thank you for your efforts. I appreciate this package very much 👍 

I have a quick question: Is there an easy way to remove highlight from standard colorpicker?

**Comment by shaunjacobsen** [comment]
Did you ever figure this out @FaresAbu-Khiarah? I resorted to hiding the option with CSS.

**Comment by premls** [comment]
@FaresAbu-Khiarah  @shaunjacobsen, Can you please share your solution?

**Comment by mdodge-ecgrow** [comment]
I know this is long afterwards, but here is the CSS I used that worked for me to remove the highlight option.
```css
.rdw-colorpicker-modal {
		width: max-content;

		.rdw-colorpicker-modal-header > span:nth-of-type(2) {
			display: none;
		}
	}
```
